site_name: "EPS88 PyEarth: A Python Introduction to Earth Science"
site_description: ""
site_author: "Weiqiang Zhu"
docs_dir: docs/
repo_name: "AI4EPS/EPS88_PyEarth"
repo_url: "https://github.com/AI4EPS/EPS88_PyEarth"
edit_uri: blob/main/docs/

nav:
  - Overview: README.md

theme:
  name: "material"
  features:
    - content.code.annotate
    - content.action.edit
    - navigation.expand

plugins:
  - mkdocs-jupyter:
      ignore_h1_titles: true
      include: ["*.ipynb"]
      ignore: []

extra:
  generator: false
  analytics:
    provider: google
    property: G-TLJF393667

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
