#!/usr/bin/env python
"""Validate a built PROJECT TRACK notebook.

check_notebook.py validates a WEEK. It is written around a week number: it looks the notebook up
by `slug` in course.yml's `schedule:`, and five of its rules ask the plan what that week teaches.
A track has no week number, no `## Homework`, no generated week summary, and — by design — no
self-checks after the loading step. Running check_notebook.py on one would either crash or report
defects that are the specification.

So this file does not weaken check_notebook. It IMPORTS it, runs every rule that is week-free and
still true of a track, skips the ones that are meaningless, and adds the handful that are specific
to `course.yml project: track_notebooks:`. Anything it skips is listed in the output, by name, so
the skip is visible rather than assumed.

    python tools/check_track.py T3
"""
import json
import pathlib
import re
import sys

import yaml

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import check_notebook as cn
import weekkit

ROOT = pathlib.Path(__file__).resolve().parent.parent
course = yaml.safe_load((ROOT / "course.yml").read_text())

# A track notebook MUST carry an AI-disclosure section — course.yml makes it one of the five
# required_of_every_project. The weekly rule bans it ("weekly notebooks carry none"). Same fact,
# opposite sign, so the pattern is dropped here and replaced by a positive rule below. Every
# other banned pattern applies to a track unchanged.
TRACK_BANNED = [(p, w) for p, w in cn.BANNED if "AI-disclosure" not in w]

# Rules that need a week number, and what a track does instead. Printed, not silently skipped.
SKIPPED = {
    "check_summary_is_generated": "no '## Week N summary'; the track summary is generated by the "
                                  "build script from modules.yml, which this file re-checks",
    "check_summary_is_this_week": "a track teaches nothing new — its summary lists what it reaches "
                                  "BACK for, so 'is it this week's module' is the wrong question",
    "check_plain_words":          "binding wording is checked below against the ideas the track "
                                  "actually quotes, not against a week's module list",
    "check_order":                "'## Homework' and '## Week N summary' do not exist in a track",
    "check_checkpoints_rebuild":  "a track has no class/homework boundary to restart across; the "
                                  "whole notebook is one pass, and execution proves it",
    "check_questions (counts)":   "7-9 questions / 5-6 in class / 2-3 homework is a week's shape; "
                                  "a track's shape is checked below instead",
}


def load(track_id):
    d = ROOT / "docs/notebooks"
    found = sorted(p for p in d.glob(f"{track_id}_*.ipynb") if "_solution" not in p.name)
    if not found:
        sys.exit(f"missing: {d}/{track_id}_*.ipynb")
    student = found[0]
    sol = student.with_name(student.stem + "_solution.ipynb")
    return (json.loads(student.read_text()),
            json.loads(sol.read_text()) if sol.exists() else None)


def check_banned(cells):
    for i, c in enumerate(cells):
        s = cn.src(c)
        for pat, why in TRACK_BANNED:
            if re.search(pat, s):
                cn.errs.append(f"cell {i}: {why}")


def check_answer_convention(cells):
    """The half of check_questions that is not a week's question budget: every ✏️ heading is
    followed by its own answer cell, and every stub is the standard one."""
    qs = [i for i, c in enumerate(cells)
          if c["cell_type"] == "markdown" and re.search(r"(?m)^\s*(#{1,4}\s*)?✏️", cn.src(c))]
    for i in qs:
        nxt = cells[i + 1] if i + 1 < len(cells) else None
        if nxt is None:
            cn.errs.append(f"question at cell {i} has no answer cell after it")
            continue
        s = cn.src(nxt)
        if nxt["cell_type"] == "markdown":
            if "Double-click" not in s:
                cn.errs.append(f"cell {i+1}: prose answer cell is missing the standard stub")
        elif "your answer here" not in s.lower():
            cn.errs.append(f"cell {i+1}: code answer cell is missing the standard stub")
    return qs


def check_scaffolding_stops(cells, qs):
    """`track_notebooks:` — "Asserts ONLY on the data-loading step".

    The whole point of a track is that the safety net is withdrawn once the data is in. An assert
    anywhere after the first question is that promise broken, and it is the one rule a track needs
    that a week does not.
    """
    asserts = [i for i, c in enumerate(cells)
               if c["cell_type"] == "code" and re.search(r"(?m)^\s*assert\b", cn.src(c))]
    if not asserts:
        cn.errs.append("no self-check at all — the loading step gets exactly one, so a student "
                       "can trust the pipeline before the help stops")
    if qs and any(i > qs[0] for i in asserts):
        after = [i for i in asserts if i > qs[0]]
        cn.errs.append(f"assert in cell(s) {after}, after the first question at cell {qs[0]} — a "
                       f"track asserts ONLY on data loading; downstream there is no single right "
                       f"answer and a self-check would be a lie about how research works")
    if not any("safety net" in cn.src(c) or "last self-check" in cn.src(c)
               for c in cells if c["cell_type"] == "markdown"):
        cn.errs.append("the notebook never TELLS the student the safety net stops — "
                       "`track_notebooks:` requires that it does")


def check_no_worked_answer(cells, solution_cells):
    """`track_notebooks:` — "a track notebook starts at solo".

    Every question's answer cell must be a stub in the student copy. If the student copy and the
    solution carry the same code under a ✏️, the question was shipped worked.
    """
    for i, (stu, sol) in enumerate(zip(cells, solution_cells or [])):
        if stu["cell_type"] != "code" or "your answer here" not in cn.src(stu).lower():
            continue
        if cn.src(stu).strip() == cn.src(sol).strip():
            cn.errs.append(f"cell {i}: the student copy and the solution are identical — the "
                           f"model answer was not deleted")


def check_required_sections(cells):
    """The five `required_of_every_project:` items appear as EMPTY headed sections."""
    text = " ".join(cn.src(c) for c in cells)
    wanted = {"one_sentence_answer": r"one[- ]sentence answer",
              "baseline_first": r"baseline",
              "split_by_structure": r"split by structure",
              "what_i_got_wrong": r"what I got wrong",
              "ai_disclosure": r"AI disclosure"}
    for key in course["project"]["required_of_every_project"]:
        name = list(key)[0]
        if not re.search(wanted[name], text, re.I):
            cn.errs.append(f"no section for the required project item `{name}`")


def check_open_question(cells, track):
    """`track_notebooks:` — "IT DOES NOT CLOSE"."""
    heads = [i for i, c in enumerate(cells) if c["cell_type"] == "markdown"
             and re.search(r"(?im)^##\s*The open question", cn.src(c))]
    if not heads:
        cn.errs.append("no '## The open question' section — a track that closes is a long week")
        return
    if heads[0] < len(cells) - 8:
        cn.errs.append(f"'## The open question' is at cell {heads[0]} of {len(cells)} — it must be "
                       f"the last thing in the notebook, because the notebook does not close")
    # The plan's own open question has to be the one on the page — the QUESTION, not the
    # paragraph of evidence course.yml wraps it in. Those figures are the plan's summary of an
    # audit; the notebook must print its own, measured from the file it just read.
    plan = re.sub(r"\s+", " ", track["open_question"]).strip()
    asked = [q.strip() for q in re.findall(r"[^.?]*\?", plan)]
    if not asked:
        cn.errs.append(f"course.yml's open_question for {track['id']} asks nothing — it has no "
                       f"question mark, so there is no question for the notebook to end on")
        return
    got = re.sub(r"\s+", " ", " ".join(cn.src(cells[i]) for i in heads))
    if not any(q in got for q in asked):
        cn.errs.append("the open question in the notebook is not the one course.yml records for "
                       "this track — one of the two has drifted")


def check_bound_wording(cells):
    """TEMPLATE 5: a plain_words sentence a notebook USES must be the recorded one, verbatim.

    A week is checked against every idea its modules own. A track owns none, so the test runs the
    other way: for each recorded idea whose NAME the notebook uses as a defined term (bolded), the
    sentence beside it must be the sentence in modules.yml.
    """
    mods = yaml.safe_load((ROOT / "modules.yml").read_text())
    raw = " ".join(cn.src(c) for c in cells if c["cell_type"] == "markdown")
    # TWO views of the same prose, and conflating them made this rule dead on its first draft.
    # `text` strips blockquote and list markers so a sentence inside "> " still matches verbatim —
    # but that strip also eats the first `*` of a line-initial `**Bootstrap:**`, so the term has to
    # be looked for in the unstripped `bold`.
    bold = re.sub(r"\s+", " ", raw)
    text = re.sub(r"\s+", " ", re.sub(r"(?m)^\s*[>*-]\s?", "", raw))
    for d in mods.get("plain_words", []):
        if f"**{d['idea']}:**" not in bold:
            continue
        want = re.sub(r"\s+", " ", d["words"]).strip()
        if want not in text:
            cn.errs.append(f"the notebook introduces '{d['idea']}' but not in its recorded "
                           f"wording — TEMPLATE 5 makes that sentence binding")


def main():
    track_id = sys.argv[1]
    track = next(t for t in course["project"]["tracks"] if t["id"] == track_id)
    student, solution = load(track_id)
    cells = student["cells"]
    sol_cells = solution["cells"] if solution else []

    figs = cn.check_pair(student, solution) if solution else 0
    check_banned(cells)
    qs = check_answer_convention(cells)
    cn.check_opening(cells)
    cn.check_conventions(cells)
    cn.check_predict(cells)
    cn.check_asserts(cells)
    cn.check_imports(cells)
    cn.check_figures(cells)
    cn.check_figures(sol_cells)
    cn.check_code_quality(cells)
    check_scaffolding_stops(cells, qs)
    check_no_worked_answer(cells, sol_cells)
    check_required_sections(cells)
    check_open_question(cells, track)
    check_bound_wording(cells)

    scope = "" if solution else " · student only (no solution in this checkout)"
    print(f"track {track_id} · {len(cells)} cells · {len(qs)} questions · {figs} figures{scope}")
    for name, why in SKIPPED.items():
        print(f"  n/a   {name}: {why}")
    for x in cn.warns:
        print(f"  warn  {x}")
    for e in cn.errs:
        print(f"  ERROR {e}")
    print("OK" if not cn.errs else f"{len(cn.errs)} error(s)")
    sys.exit(1 if cn.errs else 0)


if __name__ == "__main__":
    main()
