#!/usr/bin/env python
"""Generate SCHEDULE.md — the scannable list of weeks, topics and questions.

Generated from course.yml + modules.yml so it can never drift. Re-run after any edit:

    python tools/make_schedule.py
"""
import pathlib, yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent


def main() -> None:
    course = yaml.safe_load((ROOT / "course.yml").read_text())
    mods = {m["id"]: m for m in yaml.safe_load((ROOT / "modules.yml").read_text())["modules"]}

    out = [
        "# EPS 88 · PyEarth — Fall 2026",
        "",
        "**GENERATED by `tools/make_schedule.py` from `course.yml` and `modules.yml`. Do not edit.**",
        "",
        f"{course['meeting']} · {course['units']} units · cap {course['enrollment_cap']} · "
        "no programming assumed",
        "",
        "Libraries, whole course: " + " · ".join(f"`{l}`" for l in course["platform"]["libraries"]),
        "",
        "| Wk | Date | Topic | Field | Science question |",
        "|---|---|---|---|---|",
    ]
    for s in course["schedule"]:
        topic = " + ".join(mods[i]["title"] for i in s["modules"]) if s["modules"] else "— open —"
        out.append(f"| {s['n']} | {s['date']} | {topic} | {s['field']} | **{s['question']}** |")

    out += ["", "## Homework — same notebook, second half", "",
            "| Wk | Task |", "|---|---|"]
    for s in course["schedule"]:
        if s.get("exercise"):
            out.append(f"| {s['n']} | {s['exercise']} |")

    out += ["", "## Final project tracks", "", "| | Field | Question |", "|---|---|---|"]
    for i, tr in enumerate(course["project"]["tracks"], 1):
        out.append(f"| 14.{i} | {tr['field']} | **{tr['title']}** |")

    g = course["grading"]
    out += ["", "## Assessment", "",
            " · ".join(f"{k.replace('_', ' ')} **{v} %**" for k, v in g.items()),
            "",
            f"Due {course['policy']['exercise_due']}; solutions {course['policy']['solution_release']}.",
            "",
            f"**Final project** — pick a track notebook or bring your own question. "
            f"Lightning talks {course['project']['talks']} (RRR Monday); "
            f"notebook due {course['project']['due']}.",
            ""]

    (ROOT / "SCHEDULE.md").write_text("\n".join(out))
    print(f"SCHEDULE.md — {len(course['schedule'])} sessions, "
          f"{len(course['project']['tracks'])} project tracks")


if __name__ == "__main__":
    main()
