#!/usr/bin/env python
"""Generate mkdocs.yml from course.yml.

The previous repo's nav was hand-written and pinned to a structure that no longer existed —
eleven entries pointing at notebooks that had been replaced. Generating it means the site
cannot drift from the plan.
"""
import pathlib, yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
course = yaml.safe_load((ROOT / "course.yml").read_text())

# SCHEDULE.md lives at the repo root, outside docs_dir, so a nav entry for it 404s on the
# built site. docs/README.md already carries the week table for students.
nav = ["  - Home: README.md", "  - Weeks:"]
for s in course["schedule"]:
    if not s["modules"]:
        continue
    # Only weeks that actually exist. Listing all fourteen makes mkdocs fail on the missing
    # files and publishes dead links for weeks nobody has built yet.
    if (ROOT / "docs" / "notebooks" / f'{s["slug"]}.ipynb').exists():
        nav.append(f'    - "Week {s["n"]}: {s["question"]}": notebooks/{s["slug"]}.ipynb')

# Project tracks. They are published from the start of the term — course.yml's `choose:` says
# the track notebooks ARE the spec and a student can read ahead — so an unnavigable track is a
# track nobody can choose. Same guard as the weeks: only what exists on disk.
import glob
tracks = sorted(p for p in glob.glob(str(ROOT / "docs/notebooks/T*_*.ipynb"))
                if "_solution" not in p)
if tracks:
    nav.append("  - Projects:")
    by_id = {t["id"]: t for t in course["project"]["tracks"]}
    for p in tracks:
        stem = pathlib.Path(p).stem
        tid = stem.split("_")[0]
        title = by_id.get(tid, {}).get("title", stem)
        nav.append(f'    - "{tid}: {title}": notebooks/{stem}.ipynb')

(ROOT / "mkdocs.yml").write_text(f"""# GENERATED by tools/make_mkdocs.py from course.yml. Do not edit.
site_name: "EPS 88 — PyEarth: A Python Introduction to Earth Science"
site_author: "{course['instructor'].split('<')[0].strip()}"
docs_dir: docs/

# A solution notebook is NOT in the nav, but mkdocs publishes everything under docs_dir whether
# it is navigable or not — a --strict build copied all thirteen into the site, at guessable
# URLs. On CI they are absent (gitignored), so nothing leaked; the day one is released with
# `git add -f`, or the day anyone runs gh-deploy from a laptop, every remaining solution goes
# with it. Exclusion is the only thing standing between the release policy and the web.
exclude_docs: |
  notebooks/*_solution.ipynb
repo_name: "{course['platform']['repo'].split('github.com/')[-1]}"
repo_url: "{course['platform']['repo']}"

theme:
  name: material
  features: [navigation.sections, content.code.copy]

plugins:
  - search
  - mkdocs-jupyter:
      include_source: true

nav:
{chr(10).join(nav)}
""")
n_weeks = sum(1 for l in nav if l.strip().startswith('- "Week'))
n_tracks = sum(1 for l in nav if l.strip().startswith('- "T'))
print(f"mkdocs.yml — {n_weeks} weeks, {n_tracks} project track(s) in nav")
