#!/usr/bin/env python
"""Generate mkdocs.yml from course.yml.

The previous repo's nav was hand-written and pinned to a structure that no longer existed —
eleven entries pointing at notebooks that had been replaced. Generating it means the site
cannot drift from the plan.
"""
import pathlib, yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
course = yaml.safe_load((ROOT / "course.yml").read_text())

nav = ["  - Home: README.md", "  - Schedule: SCHEDULE.md", "  - Weeks:"]
for s in course["schedule"]:
    if not s["modules"]:
        continue
    # Only weeks that actually exist. Listing all fourteen makes mkdocs fail on the missing
    # files and publishes dead links for weeks nobody has built yet.
    if (ROOT / "docs" / "notebooks" / f'{s["slug"]}.ipynb').exists():
        nav.append(f'    - "Week {s["n"]}: {s["question"]}": notebooks/{s["slug"]}.ipynb')

(ROOT / "mkdocs.yml").write_text(f"""# GENERATED by tools/make_mkdocs.py from course.yml. Do not edit.
site_name: "EPS 88 — PyEarth: A Python Introduction to Earth Science"
site_author: "{course['instructor'].split('<')[0].strip()}"
docs_dir: docs/
repo_name: "{course['platform']['repo'].split('github.com/')[-1]}"
repo_url: "{course['platform']['repo']}"

theme:
  name: material
  features: [navigation.sections, content.code.copy]

plugins:
  - search
  - mkdocs-jupyter:
      include_source: true

nav:
{chr(10).join(nav)}
""")
print(f"mkdocs.yml — {len(nav) - 3} weeks in nav")
