#!/usr/bin/env python
"""Generate the hand-marking sheet for each week's prose question.

The autograder scores the two code parts. Part 3 is always the essay, and a paragraph cannot be
asserted on — so it is marked by hand, 46 students x 12 graded weeks = 552 reads over the term.
That is the largest recurring cost in the course that nothing else touches.

This does not mark them. It puts the question, the model answer, and the criteria on one page so
marking is a comparison rather than a fresh judgement each time, and so the standard is the same
in December as in September.

    python tools/make_rubrics.py

Criteria live in tools/rubric_criteria.yml, written once by a human (or an agent) reading each
model answer. Everything else is read out of the notebook, so a rebuild that rewords a question
regenerates the sheet rather than leaving it to drift.
"""
import json, pathlib, sys, textwrap, yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
GS = ROOT / "tools" / "gradescope"
course = yaml.safe_load((ROOT / "course.yml").read_text())
CRIT = ROOT / "tools" / "rubric_criteria.yml"
criteria = yaml.safe_load(CRIT.read_text()) if CRIT.exists() else {}


def src(c):
    return "".join(c.get("source", []))


def prose_question(cells):
    """The last ✏️ question of the homework, and the markdown answer under it.

    Last, because the course builds every week the same way: two code parts then a synthesis.
    Taking the last one rather than a pinned index means a week that adds a part still works.
    """
    hw = next((i for i, c in enumerate(cells)
               if c["cell_type"] == "markdown" and src(c).startswith("## Homework")), None)
    if hw is None:
        return None, None
    qs = [i for i in range(hw, len(cells)) if "✏️" in src(cells[i])]
    if not qs:
        return None, None
    q = qs[-1]
    # The model answer is the next markdown cell that is not itself a question.
    for j in range(q + 1, len(cells)):
        if cells[j]["cell_type"] == "markdown" and "✏️" not in src(cells[j]):
            return src(cells[q]).strip(), src(cells[j]).strip()
    return src(cells[q]).strip(), None


def sheet(n):
    w = next(s for s in course["schedule"] if s["n"] == n)
    sol = ROOT / "docs/notebooks" / f"{w['slug']}_solution.ipynb"
    if not sol.exists():
        return None
    q, model = prose_question(json.loads(sol.read_text())["cells"])
    if not q:
        return None
    spec_p = GS / f"week{n:02d}" / "spec.json"
    pts = json.loads(spec_p.read_text())["manual"]["points"] if spec_p.exists() else 25
    if pts == 0:
        return None                     # this week's parts are all auto-graded

    items = (criteria.get(n) or {}).get("items")
    if items:
        share = pts // len(items)
        crit = "\n".join(
            f"| {share if k < len(items) - 1 else pts - share * (len(items) - 1)} "
            f"| {it} |" for k, it in enumerate(items))
        crit = ("| Points | A full-credit answer does this |\n|---:|---|\n" + crit)
    else:
        crit = ("> **No criteria written yet for this week.** Add them under `"
                f"{n}:` in `tools/rubric_criteria.yml`, then re-run this. Until then, mark "
                "against the model answer below.")

    out = [f"# Week {n} — hand-marked question ({pts} points)", "",
           f"**{w['question']}**", "",
           "The autograder scores the two code parts. This is the part it cannot: mark it in "
           "Gradescope as a manual rubric item worth "
           f"{pts}, on top of the autograder's score.", "",
           "## What the student was asked", "", q, "",
           "## Criteria", "", crit, "",
           "## The model answer", "",
           "Not a template to match word for word — a student who reaches the same conclusions "
           "from their own numbers, in their own words, has answered it.", "",
           (model or "_(no model answer found — this is a defect; report it)_"), "",
           "## The week's takeaways, for context", ""]
    out += [f"{k}. {t}" for k, t in enumerate(w.get("takeaways") or [], start=1)]
    return "\n".join(out) + "\n"


made = []
for s in course["schedule"]:
    body = sheet(s["n"])
    if body is None:
        continue
    d = GS / f"week{s['n']:02d}"
    d.mkdir(parents=True, exist_ok=True)
    (d / "rubric.md").write_text(body)
    made.append(s["n"])
    has = "criteria" if (criteria.get(s["n"]) or {}).get("items") else "MODEL ANSWER ONLY"
    print(f"  week {s['n']:>2}  rubric.md  · {has}")

# One file to open on marking day, rather than thirteen.
if made:
    all_md = ["# EPS 88 — hand-marking sheets", "",
              "One page per week for the prose question the autograder cannot score. "
              "Generated by `tools/make_rubrics.py`; edit the criteria in "
              "`tools/rubric_criteria.yml`, never here.", ""]
    for n in made:
        all_md += [(GS / f"week{n:02d}" / "rubric.md").read_text(), "\n---\n"]
    (GS / "RUBRICS.md").write_text("\n".join(all_md))
    print(f"{len(made)} sheet(s) · combined in tools/gradescope/RUBRICS.md")
