#!/usr/bin/env python
"""Publish the answer keys to the PRIVATE solutions repo, for use in class.

Solutions are gitignored in the public repo and released one week at a time, so there is
nowhere to read them all at once — which is what an instructor wants in front of them while
teaching. This mirrors them into AI4EPS/EPS88_PyEarth_Solution, which is private.

    python tools/push_solutions.py            # show what would change
    python tools/push_solutions.py --push     # commit and push

It refuses to push if the target repo is not private. That check is the whole point of the
script: these files are every answer to every graded question, and a public mirror would hand
the term away in one click.
"""
import argparse, json, pathlib, shutil, subprocess, sys, tempfile, yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
REMOTE = "git@github.com:AI4EPS/EPS88_PyEarth_Solution.git"
SLUG = "AI4EPS/EPS88_PyEarth_Solution"
course = yaml.safe_load((ROOT / "course.yml").read_text())


def run(*a, **kw):
    return subprocess.run(a, capture_output=True, text=True, **kw)


def must_be_private():
    r = run("gh", "repo", "view", SLUG, "--json", "isPrivate,visibility")
    if r.returncode:
        sys.exit(f"cannot read {SLUG}: {r.stderr.strip()}")
    info = json.loads(r.stdout)
    if not info.get("isPrivate"):
        sys.exit(f"REFUSING: {SLUG} is {info.get('visibility')}, not private. These files are "
                 f"every answer to every graded question.")
    return info


def solutions():
    out = []
    for s in course["schedule"]:
        if not s.get("slug"):
            continue
        p = ROOT / "docs/notebooks" / f"{s['slug']}_solution.ipynb"
        if p.exists():
            out.append((f"week{s['n']:02d}_{s['slug']}_solution.ipynb", p, s))
    for p in sorted((ROOT / "docs/notebooks").glob("T*_solution.ipynb")):
        out.append((f"project_{p.name}", p, None))
    return out


def state(p):
    """Only ship a notebook that was actually executed — an answer key with no outputs is
    worse than none, because it looks complete and shows nothing."""
    cells = json.loads(p.read_text())["cells"]
    n = sum(1 for c in cells if c.get("outputs"))
    err = any(o.get("output_type") == "error" for c in cells for o in c.get("outputs", []))
    return len(cells), n, err


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--push", action="store_true")
    args = ap.parse_args()

    must_be_private()
    files = solutions()
    bad = [(n, p) for n, p, _ in files for c, o, e in [state(p)] if e or not o]
    for n, p in bad:
        print(f"  SKIP  {n} — not executed, or a cell ended in an error")
    files = [f for f in files if f[0] not in {n for n, _ in bad}]

    sha = run("git", "rev-parse", "--short", "HEAD", cwd=ROOT).stdout.strip()
    with tempfile.TemporaryDirectory() as tmp:
        work = pathlib.Path(tmp) / "sol"
        r = run("git", "clone", "--depth", "1", REMOTE, str(work))
        if r.returncode:                      # empty repo: clone still works but has no HEAD
            work.mkdir(parents=True, exist_ok=True)
            run("git", "init", "-q", cwd=work); run("git", "remote", "add", "origin", REMOTE, cwd=work)
        for old in work.glob("*.ipynb"):
            old.unlink()
        rows = []
        for name, p, s in files:
            shutil.copy2(p, work / name)
            c, o, _ = state(p)
            q = s["question"] if s else "project track"
            rows.append(f"| {name} | {c} | {o} | {q} |")

        (work / "README.md").write_text(
            "# EPS 88 — answer keys\n\n"
            "**Private. These are the model answers to every graded question in the course.**\n\n"
            "Generated by `tools/push_solutions.py` in `AI4EPS/EPS88_PyEarth`; do not edit here, "
            "edit the week's `tools/build_weekNN.py` and re-run the sync, or the next push "
            "overwrites your change.\n\n"
            f"Mirrored from `{sha}`. Each notebook is the executed solution: the student copy "
            "with the stubs filled in, run top to bottom on a fresh kernel.\n\n"
            "| file | cells | with output | question |\n|---|---:|---:|---|\n"
            + "\n".join(rows) + "\n")

        run("git", "add", "-A", cwd=work)
        if not run("git", "diff", "--cached", "--quiet", cwd=work).returncode:
            print("  nothing changed"); return
        print(f"  {len(files)} notebook(s) to publish, from {sha}")
        for name, _, _ in files:
            print(f"    {name}")
        if not args.push:
            print("\n  dry run — pass --push to publish"); return
        run("git", "commit", "-q", "-m", f"Answer keys from {sha}", cwd=work)
        r = run("git", "push", "-q", "origin", "HEAD:main", cwd=work)
        print("  pushed" if not r.returncode else f"  push failed: {r.stderr.strip()}")


main()
